// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgunaqwuqjlswvgaiwrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndW5hcXd1cWpsc3d2Z2Fpd3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjA5MzYsImV4cCI6MjA2NDc5NjkzNn0.PvKeE4g0gZS6YLnCyhIIG1fw7_3J5sinQ_tXSzfbLy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);